- XAgent/ai_functions/request/openai.py
> Fix typo in openai.py

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/pull_request.md
Added streamlined templates for bug reports, feature requests, and pull requests.
> Add concise GitHub templates for issues and PRs

- XAgent/tool_call_handle.py
@luyaxi can you please have a look on tis
> Fixed Typo in tool_call_handle.py

- docker-compose.yml
Replaced nerver with never
@luyaxi Please review my contribution
> Fixed Typo 

- ToolServer/README.md
> fix: fix typos in readme

- README.md
- README_JA.md
- README_ZH.md
> docs: add README_JA.md

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/testing.yaml
- .gitignore
- XAgent/agent/plan_generate_agent/prompt.py
- XAgent/agent/plan_refine_agent/prompt.py
- XAgent/config.py
- pyproject.toml
- tests/XAgent/test_config.py
1. `.gitignore`: more complete ignored files; ignore `config.yml`
2. `pyproject.toml`: init with `poetry`
3. `tests`: sample unittest with `pytest`
4. `.github/workflows/testing.yml`: running unittest for each PR or push to main
> refactor: improve Python package development cycle

- XAgent/ai_functions/request/openai.py
- tests/XAgent/test_request_openai.py
In this commit, we introduce unit tests for the `chatcompletion_request` function, which utilizes the OpenAI Chat API to generate completions based on conversation context. The unit tests ensure the correct behavior of the function under various scenarios, including error handling.
Additionally, the code has been adjusted for compatibility with OpenAI v1.x. This includes modifications to accommodate changes in the OpenAI library's structure and method calls. The function now uses OpenAI v1.x conventions while maintaining its functionality and error-handling capabilities.
These changes enhance the maintainability and reliability of the code, allowing for easier integration with future versions of the OpenAI library.
Please review the updated code and tests to ensure their correctness and …
> Add:Add unit tests for OpenAI chatcompletion_request and refactor code for OpenAI v1.x compatibility.

- dockerfiles/ToolServerNode/Dockerfile
- dockerfiles/ToolServerNode/DockerfileGPU
- dockerfiles/XAgentServer/Dockerfile
- sources.list
> fix: remove source

- XAgent/ai_functions/request/openai.py
- [🪝] Fix bug / bug 修复
azure openai v1 support
> Fix: azure openai v1 support

- README.md
- README_JA.md
- README_ZH.md
- assets/config/manager.yml
- docker-compose.yml
> Fix: docker hub support

- XAgentServer/application/main.py
- XAgentServer/application/routers/user.py
- command.py
- dockerfiles/XAgentServer/Dockerfile
> Fix: modify user and dockerfile

- docker-compose.yml
> Fix: modify health interval time

- XAgentGen/app.py
- XAgentGen/xgen/parser/function_parser.py
> FIX:tokens count in XAgentGen

- XAgent/agent/plan_generate_agent/prompt.py
Modify the two occurrences of "the" in USER_PROMPT to "not the". This may not be consistent with the task prompt during pretraining.
> fix USER_PROMPT error

- XAgent/agent/dispatcher.py
- XAgent/core.py
- XAgent/function_handler.py
- XAgent/inner_loop_search_algorithms/ReACT.py
- XAgent/recorder.py
- XAgent/toolserver_interface.py
- XAgent/workflow/task_handler.py
- XAgent/workflow/working_memory.py
- XAgentServer/application/global_val.py
- XAgentServer/application/websockets/base.py
- XAgentServer/application/websockets/recorder.py
- XAgentServer/application/websockets/replayer.py
- XAgentServer/application/websockets/share.py
- XAgentServer/server.py
- command.py
> command file upload && add log

- XAgentGen/README.md
> docs: put xagentgen docker into tool-server-network

- XAgentServer/server.py
> fix#285:web log 

- ToolServer/ToolServerNode/assets/HOW_TO_BUILD_NEW_TOOLS.md
- ToolServer/ToolServerNode/assets/HOW_TO_BUILD_NEW_TOOLS_CN.md
- [☑️] Website, documentation, demo improvements / 网站、文档、Demo 改进
增加XAgent toolservernode中关于新增工具的教学文档。
已审核。
无代码变更
无风险
> add HOW_TO_BUILD_NEW_TOOLS in CHN and ENG for guidance of adding new tools

- docker-compose.yml
Reverts OpenBMB/XAgent#294
dependency failed to start: container xagent-xagent-mysql-1 is unhealthy
> Revert "fix(docker-compose): ensure mysql starts before xagent-server"

- XAgentServer/loggers/logs.py
命令行执行任务测试，需要分析 xagent 过程时，输出的 完整log 文件没有相关的日志颜色。不便于阅读。
经过商议加上日志文件的颜色。
> fix: log file add colorful output

- XAgent/ai_functions/request/openai.py
> fix: #286 #303 adapt some azure parameters

- XAgent/ai_functions/request/openai.py
> fix: #303 adapt some 1.x version azure parameters

- XAgent/recorder.py
- XAgentServer/server.py
- docker-compose.yml
Fixed mysql start dependency issue and hide sensitive api_key information in logs
> fix: (#316) and hide sensitive api_key information in logs

- XAgent/agent/plan_generate_agent/prompt.py
- XAgent/agent/plan_refine_agent/prompt.py
> fix: change grammar typo

- ToolServer/ToolServerNode/requirements.txt
- dockerfiles/ToolServerNode/Dockerfile
- fix: add cmd to install dep httpx
#352 
> fix: add cmd to install dep httpx
